import { GetStaticProps } from "next";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { getAllPosts } from '@/lib/notionAPI'
import { title } from 'process';
import SinglePost from '@/components/Post/SinglePost'

export const getStaticProps: GetStaticProps = async () => {
  const allPosts = await getAllPosts();

  return{
    props:{
      allPosts,
    },
    revalidate: 10,
  };
};


export default function Home({ allPosts }) {
  console.log(allPosts);
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion blog
        </h1>
        {allPosts.map((post) => (
            // <div className="mx-4">
            //   {post.title}</div>
          <div className="mx-4">
            <SinglePost
            title = {post.title}
            description = {post.description}
            date = {post.date}
            tags = {post.tag}
            slug = {post.slug}
            />
          </div>
        ))}
      </main>
    </div>
  );
}
